/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralDeConhecimentoRouteImport } from './routes/central-de-conhecimento'
import { Route as ComoFuncionaOConsorcioRouteImport } from './routes/como-funciona-o-consorcio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeConhecimentoRoute = CentralDeConhecimentoRouteImport.update({
  id: '/central-de-conhecimento',
  path: '/central-de-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaOConsorcioRoute = ComoFuncionaOConsorcioRouteImport.update({
  id: '/como-funciona-o-consorcio',
  path: '/como-funciona-o-consorcio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central-de-conhecimento': typeof CentralDeConhecimentoRoute
  '/como-funciona-o-consorcio': typeof ComoFuncionaOConsorcioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central-de-conhecimento': typeof CentralDeConhecimentoRoute
  '/como-funciona-o-consorcio': typeof ComoFuncionaOConsorcioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central-de-conhecimento': typeof CentralDeConhecimentoRoute
  '/como-funciona-o-consorcio': typeof ComoFuncionaOConsorcioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/central-de-conhecimento' | '/como-funciona-o-consorcio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/central-de-conhecimento' | '/como-funciona-o-consorcio'
  id:
    '__root__' | '/' | '/central-de-conhecimento' | '/como-funciona-o-consorcio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralDeConhecimentoRoute: typeof CentralDeConhecimentoRoute
  ComoFuncionaOConsorcioRoute: typeof ComoFuncionaOConsorcioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-conhecimento': {
      id: '/central-de-conhecimento'
      path: '/central-de-conhecimento'
      fullPath: '/central-de-conhecimento'
      preLoaderRoute: typeof CentralDeConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona-o-consorcio': {
      id: '/como-funciona-o-consorcio'
      path: '/como-funciona-o-consorcio'
      fullPath: '/como-funciona-o-consorcio'
      preLoaderRoute: typeof ComoFuncionaOConsorcioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralDeConhecimentoRoute: CentralDeConhecimentoRoute,
  ComoFuncionaOConsorcioRoute: ComoFuncionaOConsorcioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
