/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralDeConhecimentoRouteImport } from './routes/central-de-conhecimento'
import { Route as ComoFuncionaOConsorcioRouteImport } from './routes/como-funciona-o-consorcio'
import { Route as IgrejasRouteImport } from './routes/igrejas'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiLeadRouteImport } from './routes/api/lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeConhecimentoRoute = CentralDeConhecimentoRouteImport.update({
  id: '/central-de-conhecimento',
  path: '/central-de-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaOConsorcioRoute = ComoFuncionaOConsorcioRouteImport.update({
  id: '/como-funciona-o-consorcio',
  path: '/como-funciona-o-consorcio',
  getParentRoute: () => rootRouteImport,
} as any)
const IgrejasRoute = IgrejasRouteImport.update({
  id: '/igrejas',
  path: '/igrejas',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central-de-conhecimento': typeof CentralDeConhecimentoRoute
  '/como-funciona-o-consorcio': typeof ComoFuncionaOConsorcioRoute
  '/igrejas': typeof IgrejasRoute
  '/obrigado': typeof ObrigadoRoute
  '/saude': typeof SaudeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/lead': typeof ApiLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central-de-conhecimento': typeof CentralDeConhecimentoRoute
  '/como-funciona-o-consorcio': typeof ComoFuncionaOConsorcioRoute
  '/igrejas': typeof IgrejasRoute
  '/obrigado': typeof ObrigadoRoute
  '/saude': typeof SaudeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/lead': typeof ApiLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central-de-conhecimento': typeof CentralDeConhecimentoRoute
  '/como-funciona-o-consorcio': typeof ComoFuncionaOConsorcioRoute
  '/igrejas': typeof IgrejasRoute
  '/obrigado': typeof ObrigadoRoute
  '/saude': typeof SaudeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/lead': typeof ApiLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/central-de-conhecimento'
    | '/como-funciona-o-consorcio'
    | '/igrejas'
    | '/obrigado'
    | '/saude'
    | '/sitemap.xml'
    | '/api/lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/central-de-conhecimento'
    | '/como-funciona-o-consorcio'
    | '/igrejas'
    | '/obrigado'
    | '/saude'
    | '/sitemap.xml'
    | '/api/lead'
  id:
    | '__root__'
    | '/'
    | '/central-de-conhecimento'
    | '/como-funciona-o-consorcio'
    | '/igrejas'
    | '/obrigado'
    | '/saude'
    | '/sitemap.xml'
    | '/api/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralDeConhecimentoRoute: typeof CentralDeConhecimentoRoute
  ComoFuncionaOConsorcioRoute: typeof ComoFuncionaOConsorcioRoute
  IgrejasRoute: typeof IgrejasRoute
  ObrigadoRoute: typeof ObrigadoRoute
  SaudeRoute: typeof SaudeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLeadRoute: typeof ApiLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-conhecimento': {
      id: '/central-de-conhecimento'
      path: '/central-de-conhecimento'
      fullPath: '/central-de-conhecimento'
      preLoaderRoute: typeof CentralDeConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona-o-consorcio': {
      id: '/como-funciona-o-consorcio'
      path: '/como-funciona-o-consorcio'
      fullPath: '/como-funciona-o-consorcio'
      preLoaderRoute: typeof ComoFuncionaOConsorcioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igrejas': {
      id: '/igrejas'
      path: '/igrejas'
      fullPath: '/igrejas'
      preLoaderRoute: typeof IgrejasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralDeConhecimentoRoute: CentralDeConhecimentoRoute,
  ComoFuncionaOConsorcioRoute: ComoFuncionaOConsorcioRoute,
  IgrejasRoute: IgrejasRoute,
  ObrigadoRoute: ObrigadoRoute,
  SaudeRoute: SaudeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLeadRoute: ApiLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
